### ISSUE TITLE
https://github.com/jumpingrivers/meetingsR

### ISSUE THREAD

**Issue by csgillespie** [benubah/r-community-explorer#1]
Hi,
Love the dashboard!

I maintain https://github.com/jumpingrivers/meetingsR

Happy to try and work together on this. For example, I've created a CSV list of groups & events at 

https://jumpingrivers.github.io/meetingsR/the-data.html

**Comment by benubah** [comment]
Great! Thanks!

We already built a dashboard displaying all R User Groups on Meetup.com (~ 613 groups) - to be announced later this month. But we are yet to include non-meetup groups and I find your data a good resource to gather information for these.

So what could be a starting point for working on user groups that are not on meetup.com? Thinking of standardizing your data (for non-meetup groups) so we could have number of members (1 by default), latitude and longitude, etc because of the leaflet map and other charts that are updated automatically with these information.

We also have plans for events (meetup and non-meetup).

If the data is significantly compatible (meetup and non-meetup), then we can read your CSV files and process them into the dashboard (and reference/credit your resources).

**Comment by csgillespie** [comment]
For non-meet-up, 

- it should be straightforward to grab the city/country and convert to lon/lat. I have code somewhere to do that if you need that.
- Members: some sites are just a web-page advertising the event, so not always possible to get the numbers of members. 

The data should be compatabile, it's just a CSV file with a row per group.

**Comment by benubah** [comment]
Okay, the data for meetup R user groups can be found here :
https://github.com/benubah/r-community-explorer/blob/master/docs/data/rugs.csv

The lon/lat data would be very helpful to have.
As per compatibility, I was thinking column-wise.

For non-meetup groups, I was thinking that it would be helpful to determine default values for columns with no known value (for. e.g. where numbers of members are not present, we put a value of 1 - since there is hardly a user group without at least one member). Please what do you think about this?

Many thanks!

**Comment by csgillespie** [comment]
- Your CSV file is very similar to the ones we [generate](https://github.com/jumpingrivers/meetingsR/blob/gh-pages/groups.csv)
- Each time a group (or event) is added to meetingsR, this CSV file is automatically updated via travis
- For missing membership, why not just use "-" or "NA". 
- lon/lat you can get using the geocode function in ggmaps

 **Compatibility**

 * Other than membership (which is just grabbed via the API), your CSV file looks very similar to the one meetingsR outputs
 * The meetingsR CSV also include the twitter handle

One option is to just use the meetingsR CSV, but with some improvements:

 * travis could run once a month and update/add the membership numbers
 * travis could include the lon/lat info as columns

That way there is one source, that you just read_csv in your app.

Thoughts?

**Comment by benubah** [comment]
@csgillespie Thank you!

**Compatibility**

I apologise that the columns you saw in the csv file are just a few of what we decided to display. We limited it because the CSV automatically renders a datatable in the dashboard. So, but the main differences I see for now between your CSV and ours are:` members`,	`datecreated`,	`past_events`,	`upcoming_events`,	`visibility`,  `lon`, `lat`
 And these columns affect several parts of the dashboard especially  the leaflet map (marker colors, critical pop-up information). I would have to think of a way of handling issues that could arise from our code when we have missing values for these.

Yes, it is possible to `read_csv()` your CSV and extract non-meetup groups.

> travis could run once a month and update/add the membership numbers

Please do you mean _update/add membership numbers_ for non-meetup or meetup groups? We already have travis updating membership numbers daily for meetup groups.

 @cvitolo @RickPack , do you have any thoughts regarding missing memberships and the general proposal for non-meetup groups?

Once more thank you @csgillespie

**Comment by csgillespie** [comment]
- Compatibility: OK. You have access to richer data for meet-ups
- travis: I'm happy to add you (or anyone else) as a member of the meetingsR repo. We could create another CSV file for the meetup groups on meetingsR. That way all info is in one place.
- We could also use your meetup list and see if any group is missing on  meetingsR

**Comment by benubah** [comment]
@csgillespie Thank you!

travis: Just to clarify, do you refer to creating another CSV file for meetup groups or non-meetup groups?

Sure it is a good thing to compare your list with our  list.

Many thanks!

**Comment by csgillespie** [comment]
We could create both:

- non-meetup
- meetup
- events

**Comment by benubah** [comment]
Hi @csgillespie 
Thanks for your proposal.
After reviewing our code (after migrating to OAuth 2.0 authentication system which involves encrypting and decrypting tokens) and other developing dashboards that already lookup our data, it is less cumbersome and much more easier for us to retain all Meetup groups within our repo.
Non-meetup groups and Events could still live within meetingsR. 

Thank you
